variable "aws_region" {
  description = "AWS region to deploy into."
  type        = string
  default     = "us-east-1"
}

variable "instance_type" {
  description = <<-EOT
    EC2 instance size for the always-on demo VM. t3.micro/t2.micro are
    free-tier eligible (750 hrs/month for 12 months on a new account) but
    are undersized for this stack in practice: Keycloak alone is a JVM
    that wants real headroom, and the guard classifier loads a DistilBERT
    model into memory on top of Postgres/Redis/Redpanda/gateway/
    control-api/console all running on the same box. t3.micro (1GB RAM)
    will likely swap heavily or OOM-kill something. t3.small (2GB) is a
    safer minimum; t3.medium (4GB) is comfortable. Start at micro only if
    you're specifically testing the free tier and are prepared to resize.
  EOT
  type        = string
  default     = "t3.micro"
}

variable "key_name" {
  description = "Name to register the SSH key pair under in AWS."
  type        = string
  default     = "warden-demo"
}

variable "public_key_path" {
  description = "Path to your local SSH public key (e.g. ~/.ssh/id_ed25519.pub) — imported as the key pair above, not generated by Terraform."
  type        = string
}

variable "ssh_allowed_cidr" {
  description = "CIDR allowed to SSH in. Default is open to the internet for convenience — narrow this to your own IP (e.g. 1.2.3.4/32) before applying for anything beyond a throwaway test."
  type        = string
  default     = "0.0.0.0/0"
}

variable "app_allowed_cidr" {
  description = "CIDR allowed to reach the app ports (gateway 8080, control-api 8081, console 3000, Keycloak 8180)."
  type        = string
  default     = "0.0.0.0/0"
}
