# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import guard_pb2 as guard__pb2


class GuardStub(object):
    """Guard scans text for prompt-injection attempts. One RPC, one job: this is
    deliberately not a general ML service — a single, strictly-latency-budgeted
    call the gateway makes on tool descriptions and tool outputs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Classify = channel.unary_unary(
                '/guard.Guard/Classify',
                request_serializer=guard__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=guard__pb2.ClassifyResponse.FromString,
                )


class GuardServicer(object):
    """Guard scans text for prompt-injection attempts. One RPC, one job: this is
    deliberately not a general ML service — a single, strictly-latency-budgeted
    call the gateway makes on tool descriptions and tool outputs.
    """

    def Classify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GuardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Classify': grpc.unary_unary_rpc_method_handler(
                    servicer.Classify,
                    request_deserializer=guard__pb2.ClassifyRequest.FromString,
                    response_serializer=guard__pb2.ClassifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'guard.Guard', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Guard(object):
    """Guard scans text for prompt-injection attempts. One RPC, one job: this is
    deliberately not a general ML service — a single, strictly-latency-budgeted
    call the gateway makes on tool descriptions and tool outputs.
    """

    @staticmethod
    def Classify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/guard.Guard/Classify',
            guard__pb2.ClassifyRequest.SerializeToString,
            guard__pb2.ClassifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
