# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guard.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bguard.proto\x12\x05guard\"\x1f\n\x0f\x43lassifyRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"P\n\x10\x43lassifyResponse\x12\x14\n\x0cis_injection\x18\x01 \x01(\x08\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x12\n\nlatency_ms\x18\x03 \x01(\x01\x32\x44\n\x05Guard\x12;\n\x08\x43lassify\x12\x16.guard.ClassifyRequest\x1a\x17.guard.ClassifyResponseBOZMgithub.com/vishnu-varma-333/warden-agent-control-plane/internal/guard/guardpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guard_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZMgithub.com/vishnu-varma-333/warden-agent-control-plane/internal/guard/guardpb'
  _globals['_CLASSIFYREQUEST']._serialized_start=22
  _globals['_CLASSIFYREQUEST']._serialized_end=53
  _globals['_CLASSIFYRESPONSE']._serialized_start=55
  _globals['_CLASSIFYRESPONSE']._serialized_end=135
  _globals['_GUARD']._serialized_start=137
  _globals['_GUARD']._serialized_end=205
# @@protoc_insertion_point(module_scope)
