// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.27.3
// source: services/guard-classifier/proto/guard.proto

package guardpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_services_guard_classifier_proto_guard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_guard_classifier_proto_guard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_services_guard_classifier_proto_guard_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ClassifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsInjection   bool                   `protobuf:"varint,1,opt,name=is_injection,json=isInjection,proto3" json:"is_injection,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`                // model's probability for the predicted class
	LatencyMs     float64                `protobuf:"fixed64,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"` // inference time, server-measured, for the latency-budget benchmark
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyResponse) Reset() {
	*x = ClassifyResponse{}
	mi := &file_services_guard_classifier_proto_guard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResponse) ProtoMessage() {}

func (x *ClassifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_guard_classifier_proto_guard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResponse.ProtoReflect.Descriptor instead.
func (*ClassifyResponse) Descriptor() ([]byte, []int) {
	return file_services_guard_classifier_proto_guard_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifyResponse) GetIsInjection() bool {
	if x != nil {
		return x.IsInjection
	}
	return false
}

func (x *ClassifyResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ClassifyResponse) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

var File_services_guard_classifier_proto_guard_proto protoreflect.FileDescriptor

const file_services_guard_classifier_proto_guard_proto_rawDesc = "" +
	"\n" +
	"+services/guard-classifier/proto/guard.proto\x12\x05guard\"%\n" +
	"\x0fClassifyRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"t\n" +
	"\x10ClassifyResponse\x12!\n" +
	"\fis_injection\x18\x01 \x01(\bR\visInjection\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x01R\tlatencyMs2D\n" +
	"\x05Guard\x12;\n" +
	"\bClassify\x12\x16.guard.ClassifyRequest\x1a\x17.guard.ClassifyResponseBOZMgithub.com/vishnu-varma-333/warden-agent-control-plane/internal/guard/guardpbb\x06proto3"

var (
	file_services_guard_classifier_proto_guard_proto_rawDescOnce sync.Once
	file_services_guard_classifier_proto_guard_proto_rawDescData []byte
)

func file_services_guard_classifier_proto_guard_proto_rawDescGZIP() []byte {
	file_services_guard_classifier_proto_guard_proto_rawDescOnce.Do(func() {
		file_services_guard_classifier_proto_guard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_guard_classifier_proto_guard_proto_rawDesc), len(file_services_guard_classifier_proto_guard_proto_rawDesc)))
	})
	return file_services_guard_classifier_proto_guard_proto_rawDescData
}

var file_services_guard_classifier_proto_guard_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_guard_classifier_proto_guard_proto_goTypes = []any{
	(*ClassifyRequest)(nil),  // 0: guard.ClassifyRequest
	(*ClassifyResponse)(nil), // 1: guard.ClassifyResponse
}
var file_services_guard_classifier_proto_guard_proto_depIdxs = []int32{
	0, // 0: guard.Guard.Classify:input_type -> guard.ClassifyRequest
	1, // 1: guard.Guard.Classify:output_type -> guard.ClassifyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_guard_classifier_proto_guard_proto_init() }
func file_services_guard_classifier_proto_guard_proto_init() {
	if File_services_guard_classifier_proto_guard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_guard_classifier_proto_guard_proto_rawDesc), len(file_services_guard_classifier_proto_guard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_guard_classifier_proto_guard_proto_goTypes,
		DependencyIndexes: file_services_guard_classifier_proto_guard_proto_depIdxs,
		MessageInfos:      file_services_guard_classifier_proto_guard_proto_msgTypes,
	}.Build()
	File_services_guard_classifier_proto_guard_proto = out.File
	file_services_guard_classifier_proto_guard_proto_goTypes = nil
	file_services_guard_classifier_proto_guard_proto_depIdxs = nil
}
